// 游戏全局配置
export const CONFIG = {
    // 渲染
    RENDERER: {
        antialias: true,
        shadowMapEnabled: true,
        shadowMapSize: 1536,
        shadowDistance: 52,      // 阴影相机覆盖半径（跟随玩家）
        toneMappingExposure: 1.45,
        maxFPS: 60,
    },

    // 世界
    WORLD: {
        size: 400,           // 地图尺寸
        fogColor: 0x8899aa,
        fogNear: 55,
        fogFar: 340,
        skyColor: 0x87a8c8,
        groundColor: 0x6b7a5a,
        sunColor: 0xffffff,
        sunIntensity: 2.8,
    },

    // 玩家
    PLAYER: {
        height: 1.7,
        crouchHeight: 1.1,
        proneHeight: 0.65,
        radius: 0.4,
        walkSpeed: 5.0,
        sprintSpeed: 8.5,
        crouchSpeed: 2.5,
        proneSpeed: 1.2,
        jumpForce: 7.0,
        gravity: 25.0,
        maxHealth: 100,
        maxArmor: 100,
        respawnTime: 5,
        // 体力系统
        maxStamina: 100,
        staminaDrainRate: 25,     // 冲刺每秒消耗
        staminaRegenRate: 15,    // 每秒恢复
        staminaRegenDelay: 2.0,  // 消耗后恢复延迟（秒）
        minSprintStamina: 10,    // 低于此值不能冲刺
        // 侧身
        leanAngle: 0.35,         // 最大侧身角度(弧度)
        leanSpeed: 6.0,          // 侧身速度
        // 重生保护
        spawnProtectionTime: 2.0, // 无敌时间(秒)
        // 冲刺到射击过渡
        // 设为 0：冲刺结束后可立即开枪（开枪无限制）
        sprintToFireDelay: 0,
        // 冲刺时 FOV 加宽量（战地风格的速度感）
        sprintFovBoost: 8,
        // 倒地/复活
        bleedOutTime: 30,           // 倒地流血时间(秒)
        downedReviveHealth: 45,     // 被复活后血量
        skipHoldTime: 1.5,          // 长按空格跳过所需时间
        skipBleedOutAccelerate: 3,  // 长按空格时bleedOut加速倍率
        // 近战（F 键，无交互目标时）
        meleeDamage: 55,
        meleeRange: 2.35,
        meleeAngle: 0.95,           // 前方扇形半角(弧度) ~54°
        meleeDuration: 0.42,        // 挥砍动画时长
        meleeHitTime: 0.18,         // 命中判定时刻
        meleeCooldown: 0.55,        // 攻击间隔
    },

    // 武器
    WEAPONS: {
        // === 突击步枪 ===
        M416: {
            name: 'M416',
            type: 'rifle',
            damage: 25,            // BF4: 25最高伤害
            minDamage: 18,         // 远距离最低伤害
            fireRate: 750,         // 高射速
            magSize: 30,
            reserveAmmo: 150,
            reloadTime: 2.1,
            range: 300,
            falloffStart: 50,      // 伤害衰减起点
            falloffEnd: 300,       // 伤害衰减终点
            spread: 0.010,         // 基础精度高
            spreadMove: 0.025,     // 移动扩散
            spreadAds: 0.003,      // 瞄准扩散
            recoil: { x: 0.004, y: 0.010, recovery: 8, pattern: 'linear' },
            recoilVRecover: 9,     // 垂直后坐力恢复速度
            recoilHRecover: 6,     // 水平后坐力恢复速度
            auto: true,
            zoom: 1.3,
            bulletSpeed: 880,
            bulletDrop: 9.8,       // 弹道下坠
            tracerColor: 0xffdd44,
            adsTime: 0.25,         // 瞄准过渡时间
            bulletSpreadRecover: 4,// 扩散恢复速度
            soundType: 'rifle_light',
            fireModes: ['auto', 'semi'],
            defaultOptic: 'holo',
            optics: ['iron', 'reflex', 'holo', 'combat3x'],
        },
        AK12: {
            name: 'AK-12',
            type: 'rifle',
            damage: 30,            // BF4: 高伤害
            minDamage: 20,
            fireRate: 650,         // 较低射速但高伤害
            magSize: 30,
            reserveAmmo: 150,
            reloadTime: 2.4,
            range: 320,
            falloffStart: 40,
            falloffEnd: 320,
            spread: 0.012,
            spreadMove: 0.030,
            spreadAds: 0.004,
            recoil: { x: 0.006, y: 0.014, recovery: 7, pattern: 'climb' },
            recoilVRecover: 7,
            recoilHRecover: 5,
            auto: true,
            zoom: 1.3,
            bulletSpeed: 850,
            bulletDrop: 9.8,
            tracerColor: 0xffdd44,
            adsTime: 0.28,
            bulletSpreadRecover: 3.5,
            soundType: 'lmg',
            fireModes: ['auto', 'semi'],
            penetration: 0.10,      // 7.62x39mm 口径，穿透力强于标准5.56mm步枪
            headshotMultiplier: 2.1, // 高伤害步枪爆头加成
            defaultOptic: 'reflex',
            optics: ['iron', 'reflex', 'holo', 'combat3x'],
        },
        SCAR_H: {
            name: 'SCAR-H',
            type: 'rifle',
            damage: 34,            // BF4: 最高伤害步枪
            minDamage: 22,
            fireRate: 600,
            magSize: 20,           // 弹匣小
            reserveAmmo: 100,
            reloadTime: 2.5,
            range: 350,
            falloffStart: 60,      // 远距离保持高伤害
            falloffEnd: 350,
            spread: 0.008,         // 精度高
            spreadMove: 0.022,
            spreadAds: 0.002,
            recoil: { x: 0.007, y: 0.016, recovery: 6, pattern: 'climb' },
            recoilVRecover: 6,
            recoilHRecover: 4,
            auto: true,
            zoom: 1.4,
            bulletSpeed: 900,
            bulletDrop: 9.8,
            tracerColor: 0xffdd44,
            adsTime: 0.30,
            bulletSpreadRecover: 3,
            soundType: 'dmr',
            fireModes: ['auto', 'semi'],
            penetration: 0.10,      // 7.62mm 口径，穿透力强于标准步枪
            headshotMultiplier: 2.2, // 高伤害步枪爆头加成
            defaultOptic: 'combat3x',
            optics: ['iron', 'reflex', 'holo', 'combat3x'],
        },
        // === 冲锋枪 ===
        MP5: {
            name: 'MP5',
            type: 'smg',
            damage: 16,            // BF4: 近距离高DPS
            minDamage: 10,
            fireRate: 800,         // 高射速
            magSize: 30,
            reserveAmmo: 150,
            reloadTime: 2.0,
            range: 150,
            falloffStart: 20,      // 衰减很快
            falloffEnd: 150,
            spread: 0.018,
            spreadMove: 0.030,
            spreadAds: 0.008,
            recoil: { x: 0.002, y: 0.006, recovery: 10, pattern: 'tight' },
            recoilVRecover: 11,
            recoilHRecover: 8,
            auto: true,
            zoom: 1.2,
            bulletSpeed: 600,
            bulletDrop: 12,
            tracerColor: 0xffdd44,
            adsTime: 0.20,
            bulletSpreadRecover: 5,
            soundType: 'smg',
            fireModes: ['auto', 'semi'],
            defaultOptic: 'reflex',
            optics: ['iron', 'reflex', 'holo'],
        },
        UMP45: {
            name: 'UMP-45',
            type: 'smg',
            damage: 22,            // .45口径高伤害
            minDamage: 12,
            fireRate: 600,
            magSize: 25,
            reserveAmmo: 125,
            reloadTime: 2.2,
            range: 160,
            falloffStart: 25,
            falloffEnd: 160,
            spread: 0.016,
            spreadMove: 0.028,
            spreadAds: 0.006,
            recoil: { x: 0.003, y: 0.008, recovery: 9, pattern: 'tight' },
            recoilVRecover: 10,
            recoilHRecover: 7,
            auto: true,
            zoom: 1.2,
            bulletSpeed: 620,
            bulletDrop: 12,
            tracerColor: 0xffdd44,
            adsTime: 0.22,
            bulletSpreadRecover: 4.5,
            soundType: 'smg',
            fireModes: ['auto', 'semi'],
            penetration: 0.06,      // .45 ACP 口径，穿透力强于9mm冲锋枪
            headshotMultiplier: 1.8, // 大口径冲锋枪爆头加成
            defaultOptic: 'holo',
            optics: ['iron', 'reflex', 'holo'],
        },
        // === 霰弹枪 ===
        M870: {
            name: 'M870',
            type: 'shotgun',
            damage: 15,            // 每颗弹丸
            pellets: 8,
            fireRate: 80,
            magSize: 7,
            reserveAmmo: 35,
            reloadTime: 3.5,
            range: 50,
            falloffStart: 15,
            falloffEnd: 50,
            spread: 0.06,          // 散布大
            spreadMove: 0.08,
            spreadAds: 0.04,       // 瞄准收束
            recoil: { x: 0.015, y: 0.038, recovery: 5, pattern: 'kick' },
            recoilVRecover: 5,
            recoilHRecover: 3,
            auto: false,
            zoom: 1.1,
            bulletSpeed: 500,
            bulletDrop: 15,
            tracerColor: 0xffaa00,
            adsTime: 0.15,
            bulletSpreadRecover: 2,
            soundType: 'shotgun',
            pumpAction: true,      // 泵动动画
            penetration: 0.02,      // 霰弹穿透力极弱
            headshotMultiplier: 1.5, // 多弹丸已具高伤害，爆头加成低
            fireModes: ['semi'],
            defaultOptic: 'iron',
            optics: ['iron', 'reflex'],
        },
        // === 狙击步枪 ===
        L96: {
            name: 'L96',
            type: 'sniper',
            damage: 95,            // BF4: 一枪爆头
            minDamage: 60,
            fireRate: 45,
            magSize: 5,
            reserveAmmo: 25,
            reloadTime: 3.0,
            range: 500,
            falloffStart: 100,     // 远距离不衰减
            falloffEnd: 500,
            spread: 0.0005,        // 极高精度
            spreadMove: 0.015,     // 移动时几乎打不准
            spreadAds: 0.0002,
            recoil: { x: 0.003, y: 0.038, recovery: 4, pattern: 'sniper' },
            recoilVRecover: 4,
            recoilHRecover: 3,
            auto: false,
            zoom: 8.0,             // 高倍镜
            bulletSpeed: 1200,
            bulletDrop: 6,         // 低弹道下坠
            tracerColor: 0xff4400,
            adsTime: 0.40,
            bulletSpreadRecover: 1,
            soundType: 'sniper',
            holdBreath: true,      // 可屏息
            penetration: 0.20,      // 高口径狙击弹，穿透力极强
            headshotMultiplier: 2.5, // 一枪爆头
            fireModes: ['semi'],
            defaultOptic: 'sniper8x',
            optics: ['combat3x', 'sniper6x', 'sniper8x'],
        },
        M40A5: {
            name: 'M40A5',
            type: 'sniper',
            damage: 85,
            minDamage: 55,
            fireRate: 55,          // 栓动略快
            magSize: 10,
            reserveAmmo: 40,
            reloadTime: 2.8,
            range: 480,
            falloffStart: 100,
            falloffEnd: 480,
            spread: 0.001,
            spreadMove: 0.016,
            spreadAds: 0.0003,
            recoil: { x: 0.003, y: 0.033, recovery: 4.5, pattern: 'sniper' },
            recoilVRecover: 4.5,
            recoilHRecover: 3.5,
            auto: false,
            zoom: 6.0,
            bulletSpeed: 1150,
            bulletDrop: 7,
            tracerColor: 0xff4400,
            adsTime: 0.38,
            bulletSpreadRecover: 1.5,
            soundType: 'sniper',
            holdBreath: true,
            penetration: 0.18,      // 栓动狙击枪穿透力强
            headshotMultiplier: 2.4, // 高爆头加成
            fireModes: ['semi'],
            defaultOptic: 'sniper6x',
            optics: ['combat3x', 'sniper6x', 'sniper8x'],
        },
        // === 轻机枪 (LMG) ===
        M249: {
            name: 'M249',
            type: 'lmg',
            damage: 26,            // BF4: 中等伤害
            minDamage: 16,
            fireRate: 800,         // 高射速
            magSize: 100,          // 大弹匣
            reserveAmmo: 200,
            reloadTime: 5.5,       // 长换弹时间
            range: 280,
            falloffStart: 40,
            falloffEnd: 280,
            spread: 0.020,         // 基础散布大
            spreadMove: 0.040,     // 移动扩散严重
            spreadAds: 0.008,      // 瞄准改善
            recoil: { x: 0.003, y: 0.008, recovery: 7, pattern: 'linear' },
            recoilVRecover: 8,
            recoilHRecover: 5,
            auto: true,
            zoom: 1.2,
            bulletSpeed: 850,
            bulletDrop: 9.8,
            tracerColor: 0xffdd44,
            adsTime: 0.35,         // 瞄准慢
            bulletSpreadRecover: 2.5,
            soundType: 'rifle_heavy',
            bipodBonus: true,      // 可架设双脚架
            suppressive: true,     // 压制效果增强
            fireModes: ['auto'],
            defaultOptic: 'reflex',
            optics: ['iron', 'reflex', 'holo', 'combat3x'],
        },
        // === 精准射手步枪 (DMR) ===
        SKS: {
            name: 'SKS',
            type: 'dmr',
            damage: 40,            // BF4: 中高伤害
            minDamage: 25,
            fireRate: 330,         // 半自动
            magSize: 20,
            reserveAmmo: 80,
            reloadTime: 2.6,
            range: 380,
            falloffStart: 60,
            falloffEnd: 380,
            spread: 0.005,         // 精度高
            spreadMove: 0.020,
            spreadAds: 0.001,
            recoil: { x: 0.003, y: 0.012, recovery: 6, pattern: 'climb' },
            recoilVRecover: 6,
            recoilHRecover: 4,
            auto: false,
            zoom: 3.5,
            bulletSpeed: 950,
            bulletDrop: 8,
            tracerColor: 0xffdd44,
            adsTime: 0.22,
            bulletSpreadRecover: 3,
            soundType: 'rifle_heavy',
            fireModes: ['semi'],
            penetration: 0.14,      // 7.62mm 口径，穿透力强
            headshotMultiplier: 2.3, // 精准射手步枪爆头加成
            defaultOptic: 'combat3x',
            optics: ['reflex', 'holo', 'combat3x', 'sniper6x'],
        },
        // === 手枪 ===
        P226: {
            name: 'P226',
            type: 'pistol',
            damage: 22,
            minDamage: 15,
            fireRate: 350,
            magSize: 12,
            reserveAmmo: 48,
            reloadTime: 1.5,
            range: 80,
            falloffStart: 30,
            falloffEnd: 80,
            spread: 0.014,
            spreadMove: 0.025,
            spreadAds: 0.008,
            recoil: { x: 0.002, y: 0.007, recovery: 10, pattern: 'tight' },
            recoilVRecover: 10,
            recoilHRecover: 8,
            auto: false,
            zoom: 1.1,
            bulletSpeed: 500,
            bulletDrop: 12,
            tracerColor: 0xffdd44,
            adsTime: 0.15,
            bulletSpreadRecover: 5,
            soundType: 'pistol',
            fireModes: ['semi'],
        },
        MP443: {
            name: 'MP443',
            type: 'pistol',
            damage: 20,
            minDamage: 13,
            fireRate: 400,         // 俄式手枪射速略快
            magSize: 17,
            reserveAmmo: 68,
            reloadTime: 1.4,
            range: 80,
            falloffStart: 30,
            falloffEnd: 80,
            spread: 0.016,
            spreadMove: 0.028,
            spreadAds: 0.010,
            recoil: { x: 0.002, y: 0.006, recovery: 11, pattern: 'tight' },
            recoilVRecover: 11,
            recoilHRecover: 9,
            auto: false,
            zoom: 1.1,
            bulletSpeed: 510,
            bulletDrop: 12,
            tracerColor: 0xffdd44,
            adsTime: 0.14,
            bulletSpreadRecover: 5.5,
            soundType: 'pistol',
            fireModes: ['semi'],
        },
        // === 火箭筒 ===
        RPG: {
            name: 'RPG-7',
            type: 'rocket',
            damage: 150,
            fireRate: 30,
            magSize: 1,
            reserveAmmo: 3,
            reloadTime: 4.0,
            range: 200,
            spread: 0.003,
            recoil: { x: 0.008, y: 0.028, recovery: 3, pattern: 'kick' },
            recoilVRecover: 3,
            recoilHRecover: 2,
            auto: false,
            zoom: 1.5,
            bulletSpeed: 150,
            tracerColor: 0xff0000,
            explosive: true,
            explosionRadius: 11,
            soundType: 'rocket',
            bulletDrop: 5,
            fireModes: ['semi'],
        },
        SMAW: {
            name: 'SMAW',
            type: 'rocket',
            damage: 180,
            fireRate: 25,
            magSize: 1,
            reserveAmmo: 2,
            reloadTime: 4.5,
            range: 250,
            spread: 0.002,
            recoil: { x: 0.010, y: 0.032, recovery: 3, pattern: 'kick' },
            recoilVRecover: 2.5,
            recoilHRecover: 2,
            auto: false,
            zoom: 1.6,
            bulletSpeed: 180,
            tracerColor: 0xff0000,
            explosive: true,
            explosionRadius: 13,
            soundType: 'rocket',
            bulletDrop: 4,
            fireModes: ['semi'],
        },
        // === 二战武器 ===
        STG44: {
            name: 'StG 44',
            type: 'rifle',
            damage: 28,
            minDamage: 20,
            fireRate: 600,
            magSize: 30,
            reserveAmmo: 120,
            reloadTime: 2.5,
            range: 300,
            falloffStart: 45,
            falloffEnd: 300,
            spread: 0.011,
            spreadMove: 0.028,
            spreadAds: 0.004,
            recoil: { x: 0.005, y: 0.013, recovery: 6.5, pattern: 'climb' },
            recoilVRecover: 6.5,
            recoilHRecover: 5,
            auto: true,
            zoom: 1.3,
            bulletSpeed: 740,
            bulletDrop: 9.8,
            tracerColor: 0xffdd44,
            adsTime: 0.28,
            bulletSpreadRecover: 3.5,
            soundType: 'rifle_heavy',
            fireModes: ['auto', 'semi'],
            penetration: 0.09,
            headshotMultiplier: 2.0,
            defaultOptic: 'iron',
            optics: ['iron', 'reflex', 'combat3x'],
        },
        Thompson: {
            name: 'Thompson',
            type: 'smg',
            damage: 20,
            minDamage: 12,
            fireRate: 700,
            magSize: 30,
            reserveAmmo: 120,
            reloadTime: 2.3,
            range: 150,
            falloffStart: 22,
            falloffEnd: 150,
            spread: 0.017,
            spreadMove: 0.030,
            spreadAds: 0.007,
            recoil: { x: 0.003, y: 0.008, recovery: 9, pattern: 'tight' },
            recoilVRecover: 9.5,
            recoilHRecover: 7,
            auto: true,
            zoom: 1.2,
            bulletSpeed: 580,
            bulletDrop: 12,
            tracerColor: 0xffdd44,
            adsTime: 0.22,
            bulletSpreadRecover: 4.5,
            soundType: 'smg',
            fireModes: ['auto', 'semi'],
            penetration: 0.06,
            headshotMultiplier: 1.8,
            defaultOptic: 'iron',
            optics: ['iron', 'reflex'],
        },
        Kar98k: {
            name: 'Kar98k',
            type: 'sniper',
            damage: 90,
            minDamage: 60,
            fireRate: 40,
            magSize: 5,
            reserveAmmo: 25,
            reloadTime: 3.2,
            range: 500,
            falloffStart: 100,
            falloffEnd: 500,
            spread: 0.0006,
            spreadMove: 0.016,
            spreadAds: 0.0002,
            recoil: { x: 0.004, y: 0.040, recovery: 3.5, pattern: 'sniper' },
            recoilVRecover: 3.5,
            recoilHRecover: 3,
            auto: false,
            zoom: 7.0,
            bulletSpeed: 1100,
            bulletDrop: 6.5,
            tracerColor: 0xff4400,
            adsTime: 0.42,
            bulletSpreadRecover: 1,
            soundType: 'sniper',
            holdBreath: true,
            penetration: 0.19,
            headshotMultiplier: 2.5,
            fireModes: ['semi'],
            defaultOptic: 'sniper6x',
            optics: ['combat3x', 'sniper6x', 'sniper8x'],
        },
        MG42: {
            name: 'MG 42',
            type: 'lmg',
            damage: 24,
            minDamage: 15,
            fireRate: 1200,        // 极高射速"希特勒的电锯"
            magSize: 50,
            reserveAmmo: 150,
            reloadTime: 6.0,
            range: 300,
            falloffStart: 45,
            falloffEnd: 300,
            spread: 0.022,
            spreadMove: 0.045,
            spreadAds: 0.009,
            recoil: { x: 0.004, y: 0.010, recovery: 6, pattern: 'linear' },
            recoilVRecover: 7,
            recoilHRecover: 4,
            auto: true,
            zoom: 1.2,
            bulletSpeed: 820,
            bulletDrop: 9.8,
            tracerColor: 0xffdd44,
            adsTime: 0.38,
            bulletSpreadRecover: 2,
            soundType: 'rifle_heavy',
            bipodBonus: true,
            suppressive: true,
            fireModes: ['auto'],
            defaultOptic: 'iron',
            optics: ['iron', 'reflex', 'combat3x'],
        },
        M1Garand: {
            name: 'M1 Garand',
            type: 'dmr',
            damage: 45,
            minDamage: 28,
            fireRate: 300,
            magSize: 8,              // 经典8发弹夹
            reserveAmmo: 48,
            reloadTime: 2.8,
            range: 400,
            falloffStart: 65,
            falloffEnd: 400,
            spread: 0.005,
            spreadMove: 0.021,
            spreadAds: 0.001,
            recoil: { x: 0.004, y: 0.014, recovery: 5.5, pattern: 'climb' },
            recoilVRecover: 5.5,
            recoilHRecover: 4,
            auto: false,
            zoom: 3.0,
            bulletSpeed: 930,
            bulletDrop: 8,
            tracerColor: 0xffdd44,
            adsTime: 0.24,
            bulletSpreadRecover: 3,
            soundType: 'rifle_heavy',
            fireModes: ['semi'],
            penetration: 0.13,
            headshotMultiplier: 2.3,
            defaultOptic: 'iron',
            optics: ['iron', 'reflex', 'combat3x'],
        },
        BAR: {
            name: 'BAR M1918',
            type: 'lmg',
            damage: 32,
            minDamage: 22,
            fireRate: 550,           // 较低射速但高伤害
            magSize: 20,
            reserveAmmo: 100,
            reloadTime: 3.2,
            range: 320,
            falloffStart: 50,
            falloffEnd: 320,
            spread: 0.014,
            spreadMove: 0.032,
            spreadAds: 0.005,
            recoil: { x: 0.005, y: 0.012, recovery: 6, pattern: 'climb' },
            recoilVRecover: 6.5,
            recoilHRecover: 4.5,
            auto: true,
            zoom: 1.3,
            bulletSpeed: 860,
            bulletDrop: 9.5,
            tracerColor: 0xffdd44,
            adsTime: 0.30,
            bulletSpreadRecover: 3,
            soundType: 'rifle_heavy',
            bipodBonus: true,
            fireModes: ['auto', 'semi'],
            defaultOptic: 'iron',
            optics: ['iron', 'reflex', 'combat3x'],
        },
        M1911: {
            name: 'M1911',
            type: 'pistol',
            damage: 28,               // .45 ACP 高伤害
            minDamage: 18,
            fireRate: 300,
            magSize: 7,
            reserveAmmo: 35,
            reloadTime: 1.6,
            range: 80,
            falloffStart: 28,
            falloffEnd: 80,
            spread: 0.013,
            spreadMove: 0.024,
            spreadAds: 0.007,
            recoil: { x: 0.003, y: 0.009, recovery: 9, pattern: 'tight' },
            recoilVRecover: 9,
            recoilHRecover: 7,
            auto: false,
            zoom: 1.1,
            bulletSpeed: 510,
            bulletDrop: 12,
            tracerColor: 0xffdd44,
            adsTime: 0.15,
            bulletSpreadRecover: 5,
            soundType: 'pistol',
            fireModes: ['semi'],
            penetration: 0.05,
            headshotMultiplier: 1.6,
        },
        P08: {
            name: 'Luger P08',
            type: 'pistol',
            damage: 22,
            minDamage: 14,
            fireRate: 380,
            magSize: 8,
            reserveAmmo: 40,
            reloadTime: 1.7,
            range: 75,
            falloffStart: 28,
            falloffEnd: 75,
            spread: 0.015,
            spreadMove: 0.026,
            spreadAds: 0.009,
            recoil: { x: 0.002, y: 0.007, recovery: 10, pattern: 'tight' },
            recoilVRecover: 10,
            recoilHRecover: 8,
            auto: false,
            zoom: 1.1,
            bulletSpeed: 500,
            bulletDrop: 12,
            tracerColor: 0xffdd44,
            adsTime: 0.14,
            bulletSpreadRecover: 5,
            soundType: 'pistol',
            fireModes: ['semi'],
        },
        Panzerschreck: {
            name: 'Panzerschreck',
            type: 'rocket',
            damage: 200,
            fireRate: 22,
            magSize: 1,
            reserveAmmo: 2,
            reloadTime: 4.8,
            range: 260,
            spread: 0.002,
            recoil: { x: 0.012, y: 0.035, recovery: 2.5, pattern: 'kick' },
            recoilVRecover: 2.5,
            recoilHRecover: 2,
            auto: false,
            zoom: 1.7,
            bulletSpeed: 160,
            tracerColor: 0xff0000,
            explosive: true,
            explosionRadius: 14,
            soundType: 'rocket',
            bulletDrop: 4.5,
            fireModes: ['semi'],
        },
    },

    // 瞄准镜/瞄具配置（集中管理，供主武器选择）
    // style 决定镜罩样式：'iron'(机械/无镜罩) / 'reflex'(反射/全息，无黑圈) / 'combat'(3-4x 战斗镜) / 'sniper'(6-8x 狙击镜)
    OPTICS: {
        iron: {
            id: 'iron',
            name: '机械瞄具',
            zoom: 1.15,
            adsTimeMult: 0.9,        // 机械瞄具更轻，开镜快
            style: 'iron',
            model: 'iron',
            tag: '近战',
        },
        reflex: {
            id: 'reflex',
            name: '反射瞄准镜',
            zoom: 1.3,
            adsTimeMult: 1.0,
            style: 'reflex',
            model: 'reflex',
            tag: '近-中距',
        },
        holo: {
            id: 'holo',
            name: '全息瞄准镜',
            zoom: 1.4,
            adsTimeMult: 1.0,
            style: 'reflex',
            model: 'holo',
            tag: '近-中距',
        },
        combat3x: {
            id: 'combat3x',
            name: '3.4x 战斗镜',
            zoom: 3.4,
            adsTimeMult: 1.25,
            style: 'combat',
            model: 'combat',
            tag: '中距',
        },
        sniper6x: {
            id: 'sniper6x',
            name: '6x 狙击镜',
            zoom: 6.0,
            adsTimeMult: 1.35,
            style: 'sniper',
            model: 'sniper',
            holdBreath: true,
            tag: '远距',
        },
        sniper8x: {
            id: 'sniper8x',
            name: '8x 狙击镜',
            zoom: 8.0,
            adsTimeMult: 1.5,
            style: 'sniper',
            model: 'sniper',
            holdBreath: true,
            tag: '远距',
        },
    },

    // 兵种
    CLASSES: {
        assault: {
            name: '突击兵',
            primary: 'M416',
            secondary: 'P226',
            gadget: 'ammobag',
            maxHealth: 110,
            maxArmor: 100,
            // 突击兵被动：冲刺体力消耗降低
            staminaDiscount: 0.3,
            // 可选武器：聚焦突击步枪
            weaponOptions: ['M416', 'AK12', 'SCAR_H', 'STG44'],
            // 特殊装备槽（原作风格反甲突击）
            special: 'hedgehog',
        },
        medic: {
            name: '医疗兵',
            primary: 'MP5',
            secondary: 'P226',
            gadget: 'medbag',
            maxHealth: 100,
            maxArmor: 100,
            // 医疗兵被动：血量低于50%时自动回血
            autoRegen: true,
            // 可选武器：聚焦冲锋枪
            weaponOptions: ['MP5', 'UMP45', 'Thompson'],
        },
        engineer: {
            name: '工程兵',
            primary: 'M870',
            secondary: 'RPG',
            gadget: 'repairtool',
            maxHealth: 120,
            maxArmor: 120,
            // 工程兵被动：对载具伤害加成
            vehicleDamageBonus: 0.3,
            // 可选武器：近战/霰弹为主，副武器 RPG 反甲
            weaponOptions: ['M870', 'UMP45', 'BAR'],
            // 专属：曲射迫击炮
            special: 'mortar',
        },
        sniper: {
            name: '侦察兵',
            primary: 'L96',
            secondary: 'MP443',
            gadget: 'sensor',
            maxHealth: 90,
            maxArmor: 80,
            // 侦察兵被动：屏息时间更长
            holdBreathBonus: 2.0,
            // 可选武器：狙击步枪 / DMR
            weaponOptions: ['L96', 'M40A5', 'SKS', 'Kar98k', 'M1Garand'],
            // 侦察兵主要依赖传感器标记
            special: null,
        },
        support: {
            name: '支援兵',
            primary: 'M249',
            secondary: 'P226',
            gadget: 'ammobag',
            maxHealth: 115,
            maxArmor: 120,
            // 支援兵被动：压制抗性
            suppressionResist: 0.4,
            // 可选武器：聚焦轻机枪
            weaponOptions: ['M249', 'MG42', 'BAR'],
            // 专属：反坦克地雷
            special: 'atmine',
        },
    },

    CLASS_SPECIALIZATIONS: {
        assault: {
            vanguard: {
                name: '先锋',
                level1: '占领权重提升至 1.20',
                level2: '占领权重提升至 1.35',
                levels: [{ captureWeight: 1.2 }, { captureWeight: 1.35 }],
            },
            grenadier: {
                name: '掷弹兵',
                level1: '手雷携带上限提升至 4',
                level2: '手雷携带上限提升至 5',
                levels: [{ grenadeMax: 4 }, { grenadeMax: 5 }],
            },
        },
        medic: {
            firstAid: {
                name: '急救',
                level1: '复活距离 3.5 米，恢复 65 生命',
                level2: '复活距离 4 米，恢复 80 生命',
                levels: [{ reviveRange: 3.5, reviveHealth: 65 }, { reviveRange: 4, reviveHealth: 80 }],
            },
            fieldHospital: {
                name: '医疗站',
                level1: '医疗包范围和持续时间提升 25%',
                level2: '医疗包范围和持续时间提升 50%',
                levels: [{ gadgetRadiusMult: 1.25, gadgetDurationMult: 1.25 }, { gadgetRadiusMult: 1.5, gadgetDurationMult: 1.5 }],
            },
        },
        engineer: {
            mechanic: {
                name: '机械师',
                level1: '维修效率提升 25%',
                level2: '维修效率提升 50%',
                levels: [{ repairMult: 1.25 }, { repairMult: 1.5 }],
            },
            antiArmor: {
                name: '破甲',
                level1: '对载具伤害加成提升至 40%',
                level2: '对载具伤害加成提升至 50%',
                levels: [{ vehicleDamageBonus: 0.4 }, { vehicleDamageBonus: 0.5 }],
            },
        },
        sniper: {
            observer: {
                name: '观察员',
                level1: '标记持续 10 秒，冷却 2.5 秒',
                level2: '标记持续 12 秒，冷却 2 秒',
                levels: [{ spotDuration: 10, spotCooldown: 2.5 }, { spotDuration: 12, spotCooldown: 2 }],
            },
            marksman: {
                name: '神射手',
                level1: '屏息倍率 2.5，压制抗性 10%',
                level2: '屏息倍率 3，压制抗性 20%',
                levels: [{ holdBreathBonus: 2.5, suppressionResist: 0.1 }, { holdBreathBonus: 3, suppressionResist: 0.2 }],
            },
        },
        support: {
            quartermaster: {
                name: '军需官',
                level1: '弹药包范围和持续时间提升 25%',
                level2: '弹药包范围和持续时间提升 50%',
                levels: [{ gadgetRadiusMult: 1.25, gadgetDurationMult: 1.25 }, { gadgetRadiusMult: 1.5, gadgetDurationMult: 1.5 }],
            },
            bulwark: {
                name: '铁壁',
                level1: '护甲 130，压制抗性 50%',
                level2: '护甲 140，压制抗性 60%',
                levels: [{ maxArmor: 130, suppressionResist: 0.5 }, { maxArmor: 140, suppressionResist: 0.6 }],
            },
        },
    },

    // 特殊装备（刺雷/地雷/迫击炮等）
    SPECIALS: {
        hedgehog: {
            name: '刺雷',
            type: 'charge',          // 手持冲锋：向前冲刺，撞到目标爆炸
            damage: 300,             // 巨大反甲爆炸
            selfDamage: 200,         // 自己也受重创（战地原版自杀式）
            radius: 6,
            chargeSpeed: 12.5,       // 冲锋速度（m/s）
            chargeDuration: 2.2,     // 冲锋持续时间
            cooldown: 10,
            antiVehicle: true,
            description: '手持刺雷向前冲锋，撞到敌人/载具爆炸，自身也受重创',
        },
        atmine: {
            name: '反坦克地雷',
            type: 'placeable',
            damage: 280,
            radius: 5,
            triggerRadius: 1.5,
            armingTime: 1.5,
            cooldown: 12,
            maxActive: 3,
            antiVehicle: true,
            description: '部署后自动引爆经过的载具',
        },
        mortar: {
            name: '迫击炮',
            type: 'mortar',          // 部署在地上 + 地图选点打击
            damage: 140,
            radius: 7,
            ammo: 6,                 // 每座迫击炮弹药数
            range: 90,
            arc: 0.9,                // 弹道弧度
            cooldown: 4,
            description: '部署迫击炮，地图选点曲射打击',
        },
        sandbag: {
            name: '沙袋掩体',
            type: 'placeable',
            cooldown: 6,
            duration: 90,
            maxActive: 3,
            description: '快速堆叠沙袋作为掩体',
        },
    },

    // 兵种技能/装备
    GADGETS: {
        ammobag: {
            name: '弹药包',
            cooldown: 15,
            duration: 10,
            radius: 5,
            type: 'deployable',
            effect: 'ammo',
        },
        medbag: {
            name: '医疗包',
            cooldown: 20,
            duration: 10,
            radius: 5,
            type: 'deployable',
            effect: 'heal',
        },
        repairtool: {
            name: '维修工具',
            cooldown: 0,
            duration: 0,
            radius: 4,
            type: 'passive',
            effect: 'repair',
        },
        sensor: {
            name: '运动传感器',
            cooldown: 25,
            duration: 12,
            radius: 30,
            type: 'deployable',
            effect: 'spot',
        },
    },

    // AI
    AI: {
        count: 10,             // 每队AI数量（Bot 内置三级距离 LOD，10/队=20总）
        reactionTime: 0.45,
        accuracy: 0.45,
        fov: Math.PI * 0.6,
        sightRange: 75,
        fireRange: 60,
        moveSpeed: 4.2,
        health: 100,
        respawnTime: 3.5,         // 彻底死亡后重生等待（秒）
        // 小队系统
        squadSize: 4,           // 每个小队人数
        squadFollowRange: 15,   // 跟随队长的距离
        // 医疗兵
        medicHealRange: 5,      // 近距离治疗范围
        medicHealAmount: 40,    // 治疗量
        medicHealCooldown: 6,   // 治疗冷却
        medicReviveSeekRange: 45, // 医疗兵主动寻找倒地队友的距离
        // 手雷
        grenadeRange: 30,       // 投掷距离
        grenadeCooldown: 15,    // 投掷冷却
        // 压制
        suppressionRange: 3,    // 子弹在此范围内产生压制
        suppressionAmount: 0.06, // 每发子弹增加的压制值（降低避免过度模糊）
        // 倒地
        botBleedOutTime: 6,     // AI倒地流血时间（秒）；过长会让战场"没人复活"
    },

    // 载具
    VEHICLES: {
        // 乘员伤害保护参数（全局）
        _crewDamageOverflow: 0.15,          // 载具吸收后溢出给乘员的比例
        _explosionCrewDamageIfAlive: 0.25,  // 爆炸对载具内存活乘员的伤害比例
        // 弹药自动恢复参数（战地风格：停火后缓慢补弹）
        _ammoRegenDelay: 5.0,               // 停止射击后多少秒开始恢复弹药
        _ammoRegenRate: 3.0,                // 每秒恢复弹药数（主炮/副武器共用）
        jeep: {
            name: '战术吉普车',
            maxHealth: 300,
            maxSpeed: 10,
            acceleration: 5.5,
            brakeForce: 12,
            turnSpeed: 1.25,
            seats: 3,
            hasWeapon: false,
            // 物理特性
            grip: 0.88,           // 抓地力（越低越容易漂移）
            driftFactor: 0.35,    // 漂移倾向
            mass: 1.0,            // 质量（影响碰撞）
            enginePitch: 1.2,     // 引擎音调倍率
            engineType: 'wheeled',// 引擎类型
            explosionRadius: 10,
            explosionDamage: 140,
            // 装甲（值=伤害倍率，越低越硬）
            armor: { front: 0.55, side: 0.75, rear: 0.9, top: 0.85 },
        },
        armedjeep: {
            name: '武装吉普',
            modelType: 'jeep',        // 复用吉普车体 + 车顶机枪塔
            maxHealth: 320,
            maxSpeed: 9.5,
            acceleration: 5.2,
            brakeForce: 12,
            turnSpeed: 1.2,
            seats: 3,
            hasWeapon: true,
            cannonDamage: 20,         // 车载重机枪
            cannonRange: 180,
            cannonCooldown: 0.09,
            cannonAmmo: 500,
            grip: 0.88,
            driftFactor: 0.32,
            mass: 1.1,
            enginePitch: 1.15,
            engineType: 'wheeled',
            explosionRadius: 10,
            explosionDamage: 150,
            armor: { front: 0.55, side: 0.75, rear: 0.9, top: 0.85 },
        },
        tank: {
            name: '主战坦克',
            maxHealth: 800,
            maxSpeed: 6,
            acceleration: 3,
            brakeForce: 8,
            turnSpeed: 0.55,
            seats: 2,
            hasWeapon: true,
            cannonDamage: 200,
            cannonRange: 300,
            cannonCooldown: 3.0,
            cannonAmmo: 20,           // 主炮弹药存量
            secondaryDamage: 18,
            secondaryRange: 180,
            secondaryCooldown: 0.08,
            secondaryAmmo: 600,       // 副武器（同轴机枪）弹药
            // 物理特性
            grip: 0.98,           // 履带高抓地
            driftFactor: 0.05,
            mass: 3.0,            // 重型
            enginePitch: 0.5,
            engineType: 'tracked',
            explosionRadius: 14,
            explosionDamage: 220,
            // 装甲（坦克最硬，正面几乎免疫小口径）
            armor: { front: 0.12, side: 0.40, rear: 0.65, top: 0.55 },
        },
        apc: {
            name: '装甲运兵车',
            maxHealth: 500,
            maxSpeed: 8,
            acceleration: 4.5,
            brakeForce: 10,
            turnSpeed: 0.8,
            seats: 4,
            hasWeapon: true,
            cannonDamage: 40,
            cannonRange: 200,
            cannonCooldown: 0.2,
            cannonAmmo: 400,          // 机炮弹药（射速快，弹药多）
            // 物理特性
            grip: 0.92,
            driftFactor: 0.2,
            mass: 2.0,
            enginePitch: 0.8,
            engineType: 'wheeled',
            explosionRadius: 12,
            explosionDamage: 180,
            // 装甲
            armor: { front: 0.30, side: 0.55, rear: 0.80, top: 0.70 },
        },
        heli: {
            name: '武装直升机',
            maxHealth: 400,
            maxSpeed: 12,
            acceleration: 3,
            brakeForce: 6,
            turnSpeed: 0.55,
            seats: 2,
            hasWeapon: true,
            cannonDamage: 60,
            cannonRange: 250,
            cannonCooldown: 0.15,
            cannonAmmo: 500,          // 机炮弹药（驾驶员）
            secondaryDamage: 25,      // 门机枪伤害（乘员位）
            secondaryRange: 200,
            secondaryCooldown: 0.08,  // 高射速机枪
            secondaryAmmo: 500,       // 门机枪弹药
            isAircraft: true,
            maxAltitude: 50,
            climbSpeed: 8,
            // 物理特性
            grip: 0.5,
            driftFactor: 0.0,
            mass: 0.8,
            enginePitch: 1.5,
            engineType: 'rotary',
            explosionRadius: 20,
            explosionDamage: 200,
            // 装甲
            armor: { front: 0.55, side: 0.70, rear: 0.85, top: 0.80 },
        },
        plane: {
            name: '攻击机',
            maxHealth: 350,
            maxSpeed: 22,             // 固定翼比直升机快
            acceleration: 4.5,
            brakeForce: 4,
            turnSpeed: 0.7,
            seats: 1,
            hasWeapon: true,
            cannonDamage: 30,         // 机头机枪
            cannonRange: 300,
            cannonCooldown: 0.1,
            cannonAmmo: 600,
            isAircraft: true,
            isPlane: true,            // 固定翼标记：需要前进速度维持升力
            maxAltitude: 70,
            climbSpeed: 9,
            grip: 0.5,
            driftFactor: 0.0,
            mass: 1.2,
            enginePitch: 1.7,
            engineType: 'rotary',
            explosionRadius: 22,
            explosionDamage: 200,
            armor: { front: 0.5, side: 0.7, rear: 0.8, top: 0.75 },
        },
        // === 二战载具 ===
        sherman: {
            name: '谢尔曼坦克',
            modelType: 'tank',        // 复用坦克模型
            maxHealth: 700,
            maxSpeed: 5.5,
            acceleration: 2.8,
            brakeForce: 7,
            turnSpeed: 0.5,
            seats: 2,
            hasWeapon: true,
            cannonDamage: 180,
            cannonRange: 280,
            cannonCooldown: 3.5,
            cannonAmmo: 18,
            secondaryDamage: 16,
            secondaryRange: 170,
            secondaryCooldown: 0.09,
            secondaryAmmo: 550,
            grip: 0.98,
            driftFactor: 0.05,
            mass: 2.8,
            enginePitch: 0.55,
            engineType: 'tracked',
            explosionRadius: 14,
            explosionDamage: 200,
            armor: { front: 0.18, side: 0.45, rear: 0.68, top: 0.58 },
        },
        tiger: {
            name: '虎式坦克',
            modelType: 'tank',        // 复用坦克模型
            maxHealth: 1000,          // 重装甲
            maxSpeed: 4.5,
            acceleration: 2.2,
            brakeForce: 6,
            turnSpeed: 0.42,
            seats: 2,
            hasWeapon: true,
            cannonDamage: 250,        // 88mm 主炮高伤害
            cannonRange: 320,
            cannonCooldown: 4.0,
            cannonAmmo: 15,
            secondaryDamage: 18,
            secondaryRange: 180,
            secondaryCooldown: 0.09,
            secondaryAmmo: 600,
            grip: 0.99,
            driftFactor: 0.03,
            mass: 3.5,               // 极重
            enginePitch: 0.42,
            engineType: 'tracked',
            explosionRadius: 16,
            explosionDamage: 250,
            armor: { front: 0.08, side: 0.32, rear: 0.55, top: 0.48 },  // 极厚装甲
        },
        kubelwagen: {
            name: '桶车',
            modelType: 'jeep',        // 复用吉普模型
            maxHealth: 280,
            maxSpeed: 11,
            acceleration: 5.8,
            brakeForce: 12,
            turnSpeed: 1.3,
            seats: 3,
            hasWeapon: false,
            grip: 0.88,
            driftFactor: 0.35,
            mass: 0.9,
            enginePitch: 1.25,
            engineType: 'wheeled',
            explosionRadius: 10,
            explosionDamage: 130,
            armor: { front: 0.58, side: 0.78, rear: 0.92, top: 0.87 },
        },
    },

    // 游戏
    GAME: {
        teamScoreLimit: 1000,
        matchDuration: 900,     // 15分钟 (秒)
        capturePointTime: 12,    // 占领时间
        capturePointPoints: 1,  // 每秒得分
        capturePointBonus: 10,  // 占领完成奖励
        // 征服模式票数系统
        ticketBleedRate: 0.8,   // 据点优势造成的每秒票数消耗
        startingTickets: 400,   // 初始票数
        deathTicketCost: 1,     // 每次死亡扣除票数
        assistScore: 5,         // 助攻得分
        assistMinDamage: 35,    // 触发助攻所需最低贡献伤害
        assistWindow: 12,       // 最后一次造成伤害后可获得助攻的秒数
        orderInterval: 35,      // 指挥命令刷新间隔
        orderCompleteBonus: 15, // 完成命令奖励
        vehicleRespawnTime: 35, // 载具被毁后重生时间
        aiVehicleStartDelay: 25,
        aiVehicleMaxPerTeam: 2,
        spotDuration: 8,
        spotCooldown: 3,
        spawnSafetyRadius: 20,
        reviveRange: 3.0,
        reviveHealth: 45,
        reviveScore: 30,
        squadReviveScore: 30,
        supplyScore: 2,
        healScore: 2,
        repairScore: 5,
        spotAssistScore: 10,
    },

    BATTLEFIELD_DIRECTOR: {
        requisition: {
            start: 25,
            max: 200,
            trailingMultiplier: 1.2,
            leadingMultiplier: 0.85,
            scoreGapForScaling: 80,
            contribution: {
                kill: 4,
                assist: 3,
                spotAssist: 3,
                capture: 12,
                revive: 8,
                support: 1,
                missionSuccess: 30,
                missionParticipation: 8,
            },
        },
        specialization: {
            level2XP: 60,
            missionXP: 20,
            contributionXP: {
                kill: 5,
                assist: 3,
                spotAssist: 3,
                capture: 10,
                revive: 8,
                support: 2,
            },
        },
        mission: {
            firstDelay: 40,
            announceDuration: 4,
            minDuration: 75,
            maxDuration: 100,
            cooldown: 40,
            thinkInterval: 0.2,
            captureHoldTime: 12,
            defendHoldTime: 22,
            supplyRadius: 10,
        },
        support: {
            globalCooldown: 40,
            typeCooldown: 75,
            maxConcurrent: 2,
            maxTargetDistance: 110,
            smoke: { cost: 60, duration: 15, radius: 12 },
            supply: { cost: 90, duration: 45, radius: 7 },
            rally: { cost: 120, duration: 75, radius: 5 },
        },
    },

    // 游戏模式
    GAME_MODES: {
        conquest: {
            id: 'conquest',
            name: '征服',
            description: '占领据点并消耗敌方票数',
            startingTickets: 400,
            ticketBleedRate: 0.8,
            capturePointPoints: 1,
            capturePointBonus: 10,
            deathTicketCost: 1,
            matchDuration: 900,
            teamScoreLimit: 1000,
            supportsStrategicObjectives: true,
            directorMissionTypes: ['attack', 'defend', 'supply', 'vehicle', 'objective'],
            enabledMaps: ['default', 'ardennes', 'normandy', 'iwojima', 'stalingrad'],
        },
        attrition: {
            id: 'attrition',
            name: '消耗战',
            description: '有限增援，医疗兵复活可节省资源',
            startingTickets: 250,
            maxReinforcements: 30,
            ticketBleedRate: 0,
            capturePointPoints: 0,
            capturePointBonus: 0,
            deathTicketCost: 1,
            matchDuration: 600,
            teamScoreLimit: 9999,
            supportsStrategicObjectives: false,
            directorMissionTypes: ['elimination', 'vehicle'],
            enabledMaps: ['default', 'ardennes', 'stalingrad'],
        },
        breakthrough: {
            id: 'breakthrough',
            name: '突破',
            description: '攻方依次突破扇区防线',
            startingTickets: 160,
            ticketReserveCap: 20,
            sectorTicketBonus: 35,
            sectorTimeBonus: 150,
            objectiveTicketBonus: 10,
            objectiveTimeBonus: 60,
            ticketBleedRate: 0,
            capturePointPoints: 0,
            capturePointBonus: 0,
            deathTicketCost: 1,
            matchDuration: 480,
            maxMatchDuration: 900,
            teamScoreLimit: 9999,
            supportsStrategicObjectives: true,
            directorMissionTypes: ['attack', 'defend', 'vehicle', 'objective'],
            enabledMaps: ['normandy', 'iwojima'],
            sectors: 3,
            capturePerSector: 2,
            capturePointTime: 30,
            attackerTeam: 0,
            sectorTicketBonus: 35,
            ticketReserveCap: 20,
            sectorTimeBonus: 150,
            transitionDuration: 8,
            overtimeDuration: 20,
        },
        tdm: {
            id: 'tdm',
            name: '团队死斗',
            description: '击杀目标轮次制，达成目标后进入下一轮',
            startingTickets: 100,
            killGoal: 50,
            maxRounds: 3,
            ticketBleedRate: 0,
            capturePointPoints: 0,
            capturePointBonus: 0,
            deathTicketCost: 1,
            matchDuration: 600,
            teamScoreLimit: 9999,
            supportsStrategicObjectives: false,
            directorMissionTypes: ['elimination'],
            enabledMaps: ['default', 'ardennes', 'stalingrad'],
        },
        rush: {
            id: 'rush',
            name: '抢攻',
            description: '攻方依次爆破 M-COM，守方拆除炸药',
            startingTickets: 120,
            ticketBleedRate: 0,
            capturePointPoints: 0,
            capturePointBonus: 0,
            deathTicketCost: 1,
            matchDuration: 900,
            teamScoreLimit: 9999,
            supportsStrategicObjectives: false,
            directorMissionTypes: [],
            enabledMaps: ['normandy', 'iwojima', 'default', 'stalingrad'],
            sectors: 3,
            fuseDuration: 40,
            attackerTeam: 0,
        },
    },

    // 地图配置
    MAPS: {
        default: {
            id: 'default',
            name: '前线突击',
            description: '开放的战场据点争夺',
            size: 400,
            terrain: {
                seed: 1337,
                frequency: 0.018,
                baseHeight: 0,
                hillHeight: 9,
                mountainHeight: 14,
                groundColor: 0x6b7a5a,
                fogColor: 0x8899aa,
                skyColor: 0x87a8c8,
                cloudCover: 0.42,
                sunColor: 0xfff3e0,
                sunElevation: 0.72,
                sunAzimuth: 0.62,
                sunIntensity: 2.8,
                toneMappingExposure: 1.45,
                ambientIntensity: 0.64,
                hemisphereIntensity: 1.05,
                hemisphereGroundColor: 0x686653,
                fillIntensity: 0.38,
                horizonBrightness: 0.16,
                grassDensity: 2000,
                grassColor: 0x5e7a3a,
            },
            environment: {
                theme: 'frontline',
                captureDetailDensity: 1.0,
                distantPropCount: 48,
            },
            capturePoints: [
                { id: 'A', name: 'A', x: -70, z: -100, label: '仓库', radius: 12 },
                { id: 'B', name: 'B', x: 0, z: 0, label: '十字路口', radius: 14 },
                { id: 'C', name: 'C', x: 70, z: 100, label: '农场', radius: 12 },
                { id: 'D', name: 'D', x: -80, z: 80, label: '高地', radius: 10 },
                { id: 'E', name: 'E', x: 80, z: -80, label: '工厂', radius: 12 },
            ],
            strategicObjectives: [
                { id: 'friendly_fuel', team: 0, name: '蓝军前线油库', shortLabel: '油库', type: 'fuel', x: -76, z: -122, health: 220, ticketDamage: 24, scoreValue: 26, effect: { vehicleRespawnDelay: 15 }, approachOffsets: [[16, 4], [12, 12], [5, 16]] },
                { id: 'enemy_fuel', team: 1, name: '红军前线油库', shortLabel: '油库', type: 'fuel', x: 76, z: 122, health: 220, ticketDamage: 24, scoreValue: 26, effect: { vehicleRespawnDelay: 15 }, approachOffsets: [[-16, -4], [-12, -12], [-5, -16]] },
                { id: 'friendly_comms', team: 0, name: '蓝军野战通讯站', shortLabel: '通讯站', type: 'comms', x: -108, z: -64, health: 180, ticketDamage: 18, scoreValue: 22, effect: { disableOrders: true }, approachOffsets: [[14, 0], [10, 10], [10, -10]] },
                { id: 'enemy_comms', team: 1, name: '红军野战通讯站', shortLabel: '通讯站', type: 'comms', x: 108, z: 64, health: 180, ticketDamage: 18, scoreValue: 22, effect: { disableOrders: true }, approachOffsets: [[-14, 0], [-10, 10], [-10, -10]] },
            ],
            tacticalLayout: {
                routes: [
                    { x: -52, z: -52, width: 92, depth: 7, rotation: Math.PI / 4, kind: 'main' },
                    { x: 52, z: 52, width: 92, depth: 7, rotation: Math.PI / 4, kind: 'main' },
                    { x: -48, z: 30, width: 96, depth: 5.5, rotation: -Math.PI / 5, kind: 'side' },
                    { x: 48, z: -30, width: 96, depth: 5.5, rotation: -Math.PI / 5, kind: 'side' },
                ],
                coverClusters: [
                    { x: -76, z: -30, rotation: 0.3, color: 0x58725c },
                    { x: 76, z: 30, rotation: -0.3, color: 0x725858 },
                    { x: -18, z: 58, rotation: 1.15, color: 0x5d6658 },
                    { x: 18, z: -58, rotation: -1.15, color: 0x665d58 },
                ],
                laneBarriers: [
                    { x: -74, z: -48, rotation: Math.PI / 4 }, { x: -52, z: -34, rotation: Math.PI / 4 },
                    { x: -28, z: -17, rotation: Math.PI / 4 }, { x: 28, z: 17, rotation: Math.PI / 4 },
                    { x: 52, z: 34, rotation: Math.PI / 4 }, { x: 74, z: 48, rotation: Math.PI / 4 },
                ],
                spawnCover: [
                    { team: 0, dx: -18, dz: 8, rotation: 0 }, { team: 0, dx: 10, dz: -16, rotation: Math.PI / 2 },
                    { team: 1, dx: 18, dz: -8, rotation: 0 }, { team: 1, dx: -10, dz: 16, rotation: Math.PI / 2 },
                ],
                landmarks: [
                    { type: 'helipad', x: -82, z: -66, team: 0 }, { type: 'helipad', x: 82, z: 66, team: 1 },
                    { type: 'comms', x: -6, z: 6 },
                    { type: 'sign', x: -64, z: -30, label: 'B' }, { type: 'sign', x: 64, z: 30, label: 'E', color: 0x6f5555 },
                    { type: 'checkpoint', x: -138, z: -104, rotation: Math.PI / 4, team: 0 },
                    { type: 'checkpoint', x: 138, z: 104, rotation: Math.PI / 4, team: 1 },
                ],
            },
            vehicleSpawns: [
                { type: 'jeep', x: -80, z: -130, team: 0, yaw: 0.5 },
                { type: 'tank', x: -85, z: -125, team: 0, yaw: 0.3 },
                { type: 'armedjeep', x: -75, z: -135, team: 0, yaw: 0.5 },
                { type: 'plane', x: -95, z: -140, team: 0, yaw: 0.5 },
                { type: 'jeep', x: 80, z: 130, team: 1, yaw: -0.5 },
                { type: 'tank', x: 85, z: 125, team: 1, yaw: -0.3 },
                { type: 'armedjeep', x: 75, z: 135, team: 1, yaw: -0.5 },
                { type: 'plane', x: 95, z: 140, team: 1, yaw: -0.5 + Math.PI },
            ],
            spawnAreas: {
                0: { center: { x: -85, z: -130 }, radius: 12 },
                1: { center: { x: 85, z: 130 }, radius: 12 },
            },
            obstacles: { buildings: 18, walls: 24, sandbags: 30, crates: 40, trees: 60 },
        },
        ardennes: {
            id: 'ardennes',
            name: '阿登森林',
            description: '雪地林区的近距离战斗',
            size: 400,
            terrain: {
                seed: 4242,
                frequency: 0.022,
                baseHeight: 2,
                hillHeight: 11,
                mountainHeight: 18,
                groundColor: 0xdde5ee,
                fogColor: 0xaabbcc,
                skyColor: 0xb8c8d8,
                cloudCover: 0.78,
                sunColor: 0xdde8f8,
                sunIntensity: 2.25,
                sunElevation: 0.45,
                sunAzimuth: 0.42,
                toneMappingExposure: 1.34,
                ambientIntensity: 0.68,
                hemisphereIntensity: 1.08,
                hemisphereGroundColor: 0xaeb8b5,
                fillIntensity: 0.34,
                horizonBrightness: 0.2,
                fogNear: 42,
                fogFar: 250,
                grassDensity: 450,
                grassColor: 0x8a8f78,
            },
            environment: {
                theme: 'forest',
                captureDetailDensity: 0.9,
                distantPropCount: 62,
            },
            capturePoints: [
                { id: 'A', name: 'A', x: -60, z: -80, label: '林间小屋', radius: 12 },
                { id: 'B', name: 'B', x: 0, z: -20, label: '桥头', radius: 14 },
                { id: 'C', name: 'C', x: 60, z: 80, label: '山脊', radius: 10 },
            ],
            strategicObjectives: [
                { id: 'friendly_fuel', team: 0, name: '盟军林间油料站', shortLabel: '油料站', type: 'fuel', x: -66, z: -102, health: 220, ticketDamage: 24, scoreValue: 26, effect: { vehicleRespawnDelay: 15 }, approachOffsets: [[14, 5], [10, 13], [5, 16]] },
                { id: 'enemy_fuel', team: 1, name: '轴心林间油料站', shortLabel: '油料站', type: 'fuel', x: 66, z: 102, health: 220, ticketDamage: 24, scoreValue: 26, effect: { vehicleRespawnDelay: 15 }, approachOffsets: [[-14, -5], [-10, -13], [-5, -16]] },
                { id: 'friendly_comms', team: 0, name: '盟军山林电台', shortLabel: '山林电台', type: 'comms', x: -82, z: -48, health: 180, ticketDamage: 18, scoreValue: 22, effect: { disableOrders: true }, approachOffsets: [[13, 4], [9, 12], [12, -7]] },
                { id: 'enemy_comms', team: 1, name: '轴心山脊电台', shortLabel: '山脊电台', type: 'comms', x: 82, z: 48, health: 180, ticketDamage: 18, scoreValue: 22, effect: { disableOrders: true }, approachOffsets: [[-13, -4], [-9, -12], [-12, 7]] },
            ],
            tacticalLayout: {
                routes: [
                    { x: -36, z: -58, width: 80, depth: 5.5, rotation: 0.64, kind: 'main' },
                    { x: 28, z: 28, width: 92, depth: 5.5, rotation: 0.74, kind: 'main' },
                    { x: -54, z: 18, width: 78, depth: 4.2, rotation: -0.42, kind: 'side' },
                    { x: 46, z: 54, width: 68, depth: 4.2, rotation: 0.2, kind: 'side' },
                ],
                coverClusters: [
                    { x: -48, z: -38, rotation: 0.7, color: 0x5d6658 },
                    { x: -6, z: -18, rotation: 1.25, color: 0x70756c },
                    { x: 42, z: 52, rotation: 0.55, color: 0x665f58 },
                ],
                laneBarriers: [
                    { x: -46, z: -54, rotation: 0.65 }, { x: -21, z: -34, rotation: 0.65 },
                    { x: 14, z: 7, rotation: 0.74 }, { x: 39, z: 33, rotation: 0.74 },
                    { x: 55, z: 61, rotation: 0.2 },
                ],
                spawnCover: [
                    { team: 0, dx: -14, dz: 10, rotation: 0.35 }, { team: 0, dx: 12, dz: -12, rotation: 1.4 },
                    { team: 1, dx: 14, dz: -10, rotation: 0.35 }, { team: 1, dx: -12, dz: 12, rotation: 1.4 },
                ],
                landmarks: [
                    { type: 'checkpoint', x: -100, z: -88, rotation: 0.7, team: 0 },
                    { type: 'checkpoint', x: 98, z: 88, rotation: 0.7, team: 1 },
                    { type: 'comms', x: -4, z: -12 },
                    { type: 'sign', x: -38, z: -45, label: '桥头' }, { type: 'sign', x: 42, z: 56, label: '山脊', color: 0x626b5d },
                ],
            },
            vehicleSpawns: [
                { type: 'jeep', x: -70, z: -110, team: 0, yaw: 0.5 },
                { type: 'apc', x: -75, z: -105, team: 0, yaw: 0.3 },
                { type: 'jeep', x: 70, z: 110, team: 1, yaw: -0.5 },
                { type: 'apc', x: 75, z: 105, team: 1, yaw: -0.3 },
            ],
            spawnAreas: {
                0: { center: { x: -75, z: -110 }, radius: 12 },
                1: { center: { x: 75, z: 110 }, radius: 12 },
            },
            obstacles: { buildings: 12, walls: 18, sandbags: 25, crates: 30, trees: 100 },
        },
        normandy: {
            id: 'normandy',
            name: '诺曼底海滩',
            description: '登陆作战与海岸突破',
            size: 400,
            terrain: {
                seed: 7777,
                frequency: 0.015,
                baseHeight: 0,
                hillHeight: 8,
                mountainHeight: 12,
                groundColor: 0x8a8068,
                fogColor: 0x99aabb,
                skyColor: 0x7a98b8,
                cloudCover: 0.58,
                sunColor: 0xffeacc,
                sunIntensity: 2.7,
                sunElevation: 0.55,
                sunAzimuth: 0.78,
                toneMappingExposure: 1.48,
                ambientIntensity: 0.66,
                hemisphereIntensity: 1.08,
                hemisphereGroundColor: 0x777569,
                fillIntensity: 0.4,
                horizonBrightness: 0.18,
                grassDensity: 420,
                grassColor: 0x7d8455,
                coast: {
                    direction: 'positiveZ',
                    start: 160,
                    transition: 28,
                    waterLevel: 0.55,
                    underwaterDepth: 7,
                },
            },
            environment: {
                theme: 'beach',
                captureDetailDensity: 1.15,
                distantPropCount: 44,
            },
            water: { level: 0.55, color: 0x35586b, deepColor: 0x1a3547 },
            capturePoints: [
                { id: 'A', name: 'A', x: 0, z: 120, label: '滩头', radius: 16 },
                { id: 'B', name: 'B', x: 0, z: 60, label: '海堤', radius: 14 },
                { id: 'C', name: 'C', x: 0, z: 0, label: '小镇', radius: 14 },
                { id: 'D', name: 'D', x: 0, z: -60, label: '高地碉堡', radius: 12 },
            ],
            breakthroughSectors: [['A'], ['B', 'C'], ['D']],
            strategicObjectives: [
                { id: 'friendly_fuel', team: 0, name: '登陆舰油料集散点', shortLabel: '油料集散点', type: 'fuel', x: -24, z: 146, health: 220, ticketDamage: 24, scoreValue: 26, effect: { vehicleRespawnDelay: 15 }, approachOffsets: [[15, -4], [10, -12], [2, -16]] },
                { id: 'enemy_fuel', team: 1, name: '高地装甲油库', shortLabel: '装甲油库', type: 'fuel', x: 22, z: -88, health: 220, ticketDamage: 24, scoreValue: 26, effect: { vehicleRespawnDelay: 15 }, approachOffsets: [[-14, 5], [-9, 13], [1, 16]] },
                { id: 'friendly_comms', team: 0, name: '滩头海军电台', shortLabel: '海军电台', type: 'comms', x: 54, z: 132, health: 180, ticketDamage: 18, scoreValue: 22, effect: { disableOrders: true }, approachOffsets: [[-13, -3], [-9, -11], [2, -14]] },
                { id: 'enemy_comms', team: 1, name: '高地火控站', shortLabel: '火控站', type: 'comms', x: -42, z: -72, health: 180, ticketDamage: 18, scoreValue: 22, effect: { disableOrders: true }, approachOffsets: [[13, 4], [9, 12], [-2, 15]] },
            ],
            tacticalLayout: {
                routes: [
                    { x: 0, z: 96, width: 78, depth: 8, rotation: Math.PI / 2, kind: 'main' },
                    { x: 0, z: 24, width: 72, depth: 7, rotation: Math.PI / 2, kind: 'main' },
                    { x: -36, z: 58, width: 72, depth: 4.5, rotation: 1.23, kind: 'side' },
                    { x: 38, z: 4, width: 84, depth: 4.5, rotation: 1.86, kind: 'side' },
                ],
                coverClusters: [
                    { x: -34, z: 112, rotation: 0, color: 0x777267 },
                    { x: 32, z: 76, rotation: 0.15, color: 0x6c6755 },
                    { x: -30, z: 18, rotation: 1.5, color: 0x5d625f },
                    { x: 26, z: -42, rotation: 1.45, color: 0x68645d },
                ],
                laneBarriers: [
                    { x: -28, z: 100, rotation: 0 }, { x: 28, z: 100, rotation: 0 },
                    { x: -24, z: 62, rotation: 0 }, { x: 24, z: 62, rotation: 0 },
                    { x: -20, z: 8, rotation: 0 }, { x: 20, z: 8, rotation: 0 },
                ],
                spawnCover: [
                    { team: 0, dx: -30, dz: -2, rotation: 0 }, { team: 0, dx: 30, dz: -2, rotation: 0 },
                    { team: 1, dx: -18, dz: 12, rotation: 0 }, { team: 1, dx: 18, dz: 12, rotation: 0 },
                ],
                landmarks: [
                    { type: 'checkpoint', x: -42, z: 72, rotation: 0, team: 0 },
                    { type: 'checkpoint', x: 42, z: 72, rotation: 0, team: 0 },
                    { type: 'sign', x: -28, z: 60, label: '海堤' }, { type: 'sign', x: 26, z: -50, label: '高地', color: 0x625d54 },
                    { type: 'industrial', x: 56, z: -30, rotation: 0 },
                ],
            },
            vehicleSpawns: [
                { type: 'tank', x: -15, z: 140, team: 0, yaw: 0 },
                { type: 'armedjeep', x: 15, z: 140, team: 0, yaw: 0 },
                { type: 'tank', x: 15, z: -80, team: 1, yaw: Math.PI },
                { type: 'apc', x: -15, z: -80, team: 1, yaw: Math.PI },
            ],
            spawnAreas: {
                0: { center: { x: 0, z: 140 }, radius: 15 },
                1: { center: { x: 0, z: -90 }, radius: 12 },
            },
            // 诺曼底是海滩登陆图，树木再压低，优先灌木/掩体
            obstacles: { buildings: 20, walls: 30, sandbags: 40, crates: 35, trees: 8 },
        },
        iwojima: {
            id: 'iwojima',
            name: '硫磺岛',
            description: '火山岛屿的残酷争夺',
            size: 400,
            terrain: {
                seed: 9999,
                frequency: 0.018,
                baseHeight: 0,
                hillHeight: 12,
                mountainHeight: 22,
                groundColor: 0x5c554b,
                fogColor: 0x6e7f8e,
                skyColor: 0x7fa0b3,
                cloudCover: 0.6,
                sunColor: 0xffd9b0,
                sunIntensity: 2.85,
                sunElevation: 0.5,
                sunAzimuth: 0.7,
                toneMappingExposure: 1.52,
                ambientIntensity: 0.7,
                hemisphereIntensity: 1.12,
                hemisphereGroundColor: 0x514c46,
                fillIntensity: 0.42,
                horizonBrightness: 0.2,
                fogNear: 50,
                fogFar: 300,
                grassDensity: 600,
                grassColor: 0x5a6248,
            },
            environment: {
                theme: 'volcanic',
                captureDetailDensity: 1.1,
                distantPropCount: 52,
            },
            water: { level: 0.45, color: 0x2c4a58, deepColor: 0x14293a },
            capturePoints: [
                { id: 'A', name: 'A', x: 0, z: 130, label: '海滩', radius: 16 },
                { id: 'B', name: 'B', x: -40, z: 50, label: '机场', radius: 14 },
                { id: 'C', name: 'C', x: 40, z: -20, label: '矿井', radius: 12 },
                { id: 'D', name: 'D', x: 0, z: -80, label: '折钵山', radius: 10 },
            ],
            breakthroughSectors: [['A'], ['B', 'C'], ['D']],
            strategicObjectives: [
                { id: 'friendly_fuel', team: 0, name: '滩头航空油料场', shortLabel: '航空油料场', type: 'fuel', x: -28, z: 148, health: 220, ticketDamage: 24, scoreValue: 26, effect: { vehicleRespawnDelay: 15 }, approachOffsets: [[15, -3], [10, -12], [1, -16]] },
                { id: 'enemy_fuel', team: 1, name: '折钵山洞库', shortLabel: '山洞油库', type: 'fuel', x: 18, z: -104, health: 220, ticketDamage: 24, scoreValue: 26, effect: { vehicleRespawnDelay: 15 }, approachOffsets: [[-14, 5], [-9, 13], [2, 16]] },
                { id: 'friendly_comms', team: 0, name: '登陆指挥电台', shortLabel: '指挥电台', type: 'comms', x: 48, z: 132, health: 180, ticketDamage: 18, scoreValue: 22, effect: { disableOrders: true }, approachOffsets: [[-13, -4], [-8, -12], [3, -14]] },
                { id: 'enemy_comms', team: 1, name: '折钵山观察所', shortLabel: '观察所', type: 'comms', x: -38, z: -82, health: 180, ticketDamage: 18, scoreValue: 22, effect: { disableOrders: true }, approachOffsets: [[13, 5], [9, 12], [-2, 15]] },
            ],
            tacticalLayout: {
                routes: [
                    { x: -18, z: 92, width: 84, depth: 7, rotation: 1.78, kind: 'main' },
                    { x: 20, z: 18, width: 86, depth: 7, rotation: 1.28, kind: 'main' },
                    { x: -48, z: 38, width: 76, depth: 4.5, rotation: 1.05, kind: 'side' },
                    { x: 50, z: -46, width: 72, depth: 4.5, rotation: 1.95, kind: 'side' },
                ],
                coverClusters: [
                    { x: -42, z: 112, rotation: 0.25, color: 0x57524b },
                    { x: -38, z: 48, rotation: 1.0, color: 0x66615a },
                    { x: 38, z: 2, rotation: 1.45, color: 0x4f5553 },
                    { x: -12, z: -64, rotation: 0.2, color: 0x56514b },
                ],
                laneBarriers: [
                    { x: -34, z: 105, rotation: 0.2 }, { x: 18, z: 88, rotation: 0.2 },
                    { x: -34, z: 42, rotation: 1.05 }, { x: 25, z: 18, rotation: 1.28 },
                    { x: 36, z: -42, rotation: 1.95 },
                ],
                spawnCover: [
                    { team: 0, dx: -30, dz: -2, rotation: 0.1 }, { team: 0, dx: 28, dz: -6, rotation: -0.1 },
                    { team: 1, dx: -18, dz: 12, rotation: 0.15 }, { team: 1, dx: 18, dz: 12, rotation: -0.15 },
                ],
                landmarks: [
                    { type: 'helipad', x: -52, z: 126, team: 0 },
                    { type: 'checkpoint', x: -48, z: 72, rotation: 0.2, team: 0 },
                    { type: 'sign', x: -42, z: 50, label: '机场' }, { type: 'sign', x: 40, z: -18, label: '矿井', color: 0x57524b },
                    { type: 'comms', x: -12, z: -70 },
                ],
            },
            vehicleSpawns: [
                { type: 'jeep', x: -15, z: 145, team: 0, yaw: 0 },
                { type: 'tank', x: 15, z: 145, team: 0, yaw: 0 },
                { type: 'jeep', x: 15, z: -95, team: 1, yaw: Math.PI },
                { type: 'tank', x: -15, z: -95, team: 1, yaw: Math.PI },
            ],
            spawnAreas: {
                0: { center: { x: 0, z: 145 }, radius: 15 },
                1: { center: { x: 0, z: -100 }, radius: 12 },
            },
            obstacles: { buildings: 10, walls: 20, sandbags: 35, crates: 25, trees: 30 },
        },
        stalingrad: {
            id: 'stalingrad',
            name: '斯大林格勒',
            description: '废墟巷战与近距离据点争夺',
            size: 400,
            terrain: {
                seed: 1942,
                frequency: 0.02,
                baseHeight: 0,
                hillHeight: 7,
                mountainHeight: 11,
                groundColor: 0x6a655c,
                fogColor: 0x8a8e92,
                skyColor: 0x8a9aaa,
                cloudCover: 0.7,
                sunColor: 0xffe8c8,
                sunIntensity: 2.4,
                sunElevation: 0.42,
                sunAzimuth: 0.55,
                toneMappingExposure: 1.4,
                ambientIntensity: 0.68,
                hemisphereIntensity: 1.05,
                hemisphereGroundColor: 0x5a564c,
                fillIntensity: 0.36,
                horizonBrightness: 0.14,
                fogNear: 40,
                fogFar: 260,
                grassDensity: 280,
                grassColor: 0x5a6248,
            },
            environment: {
                theme: 'urban_ruin',
                captureDetailDensity: 1.2,
                distantPropCount: 56,
            },
            capturePoints: [
                { id: 'A', name: 'A', x: -70, z: -70, label: '火车站', radius: 12 },
                { id: 'B', name: 'B', x: 0, z: 0, label: '中央广场', radius: 14 },
                { id: 'C', name: 'C', x: 70, z: 70, label: '工厂废墟', radius: 12 },
                { id: 'D', name: 'D', x: -50, z: 60, label: '公寓楼', radius: 11 },
                { id: 'E', name: 'E', x: 50, z: -60, label: '弹药库', radius: 11 },
            ],
            strategicObjectives: [
                { id: 'friendly_fuel', team: 0, name: '火车站燃料仓', shortLabel: '燃料仓', type: 'fuel', x: -112, z: -118, health: 220, ticketDamage: 24, scoreValue: 26, effect: { vehicleRespawnDelay: 15 }, approachOffsets: [[15, 4], [11, 12], [4, 16]] },
                { id: 'enemy_fuel', team: 1, name: '工厂装甲油库', shortLabel: '装甲油库', type: 'fuel', x: 112, z: 118, health: 220, ticketDamage: 24, scoreValue: 26, effect: { vehicleRespawnDelay: 15 }, approachOffsets: [[-15, -4], [-11, -12], [-4, -16]] },
                { id: 'friendly_comms', team: 0, name: '铁路调度站', shortLabel: '调度站', type: 'comms', x: -104, z: -42, health: 180, ticketDamage: 18, scoreValue: 22, effect: { disableOrders: true }, approachOffsets: [[14, 1], [10, 10], [10, -10]] },
                { id: 'enemy_comms', team: 1, name: '工厂指挥所', shortLabel: '指挥所', type: 'comms', x: 104, z: 42, health: 180, ticketDamage: 18, scoreValue: 22, effect: { disableOrders: true }, approachOffsets: [[-14, -1], [-10, 10], [-10, -10]] },
            ],
            tacticalLayout: {
                routes: [
                    { x: 0, z: 0, width: 170, depth: 8, rotation: Math.PI / 4, kind: 'main' },
                    { x: -18, z: 42, width: 118, depth: 6, rotation: 0, kind: 'main' },
                    { x: 22, z: -46, width: 118, depth: 6, rotation: 0, kind: 'main' },
                    { x: -62, z: 12, width: 86, depth: 4.5, rotation: Math.PI / 2, kind: 'side' },
                    { x: 62, z: -12, width: 86, depth: 4.5, rotation: Math.PI / 2, kind: 'side' },
                ],
                coverClusters: [
                    { x: -58, z: -42, rotation: 0.1, color: 0x666159 },
                    { x: -36, z: 54, rotation: 1.5, color: 0x6e6258 },
                    { x: 12, z: 6, rotation: 0.75, color: 0x655f58 },
                    { x: 52, z: -50, rotation: 1.5, color: 0x665852 },
                    { x: 64, z: 42, rotation: 0.1, color: 0x705852 },
                ],
                laneBarriers: [
                    { x: -70, z: -70, rotation: Math.PI / 4 }, { x: -40, z: -40, rotation: Math.PI / 4 },
                    { x: -10, z: -10, rotation: Math.PI / 4 }, { x: 20, z: 20, rotation: Math.PI / 4 },
                    { x: 50, z: 50, rotation: Math.PI / 4 },
                    { x: -48, z: 42, rotation: 0 }, { x: 50, z: -46, rotation: 0 },
                ],
                spawnCover: [
                    { team: 0, dx: -18, dz: 8, rotation: 0.15 }, { team: 0, dx: 10, dz: -18, rotation: Math.PI / 2 },
                    { team: 1, dx: 18, dz: -8, rotation: 0.15 }, { team: 1, dx: -10, dz: 18, rotation: Math.PI / 2 },
                ],
                landmarks: [
                    { type: 'checkpoint', x: -126, z: -92, rotation: Math.PI / 4, team: 0 },
                    { type: 'checkpoint', x: 126, z: 92, rotation: Math.PI / 4, team: 1 },
                    { type: 'industrial', x: 76, z: 48, rotation: 0.2 },
                    { type: 'comms', x: -96, z: -34 },
                    { type: 'sign', x: -62, z: -62, label: '火车站' }, { type: 'sign', x: 64, z: 56, label: '工厂', color: 0x705852 },
                ],
            },
            vehicleSpawns: [
                { type: 'jeep', x: -85, z: -100, team: 0, yaw: 0.4 },
                { type: 'tank', x: -90, z: -95, team: 0, yaw: 0.3 },
                { type: 'armedjeep', x: -78, z: -105, team: 0, yaw: 0.5 },
                { type: 'jeep', x: 85, z: 100, team: 1, yaw: -0.4 },
                { type: 'tank', x: 90, z: 95, team: 1, yaw: -0.3 },
                { type: 'armedjeep', x: 78, z: 105, team: 1, yaw: -0.5 },
            ],
            spawnAreas: {
                0: { center: { x: -90, z: -105 }, radius: 14 },
                1: { center: { x: 90, z: 105 }, radius: 14 },
            },
            obstacles: { buildings: 28, walls: 36, sandbags: 45, crates: 50, trees: 12 },
        },
    },

    FORTIFICATIONS: {
        placeDistance: 3.5,
        rotationStep: Math.PI / 12,
        cooldown: 3,
        validationInterval: 0.1,
        boundaryPadding: 5,
        types: {
            sandbag: {
                name: '沙袋墙',
                width: 2.6,
                height: 1.0,
                depth: 0.7,
                health: 300,
                armorMultiplier: 0.75,
                breakType: 'deform',
                maxCount: 5,
                maxGroundDelta: 0.42,
            },
            wire: {
                name: '铁丝网',
                width: 3.2,
                height: 1.1,
                depth: 0.9,
                health: 160,
                armorMultiplier: 0.9,
                breakType: 'shatter',
                maxCount: 3,
                maxGroundDelta: 0.5,
            },
            hedgehog: {
                name: '反坦克桩',
                width: 1.7,
                height: 1.5,
                depth: 1.7,
                health: 500,
                armorMultiplier: 0.35,
                breakType: 'shatter',
                maxCount: 2,
                maxGroundDelta: 0.6,
            },
        },
    },

    // 可破坏实体配置
    DESTRUCTIBLES: {
        building: { health: 220, armorMultiplier: 0.65, breakType: 'collapse' },
        wall: { health: 120, armorMultiplier: 0.8, breakType: 'shatter' },
        sandbag: { health: 200, armorMultiplier: 0.8, breakType: 'deform' },
        crate: { health: 60, armorMultiplier: 1.0, breakType: 'shatter' },
        fence: { health: 40, armorMultiplier: 1.0, breakType: 'shatter' },
    },

    // 队伍
    TEAMS: {
        friendly: { id: 0, name: '我方', color: 0x0088ff, markerColor: 0x00aaff },
        enemy: { id: 1, name: '敌方', color: 0xff3300, markerColor: 0xff4444 },
    },
};
